version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - TYPEORM_CONNECTION=sqlite
      - TYPEORM_DATABASE=db.sqlite
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=true
      - TYPEORM_ENTITIES=dist/models/*.js
      - TYPEORM_MIGRATIONS=dist/migrations/*.js
      - TYPEORM_MIGRATIONS_DIR=src/migrations

  db:
    image: nouchka/sqlite3
    volumes:
      - sqlite-data:/var/lib/sqlite3

volumes:
  sqlite-data:
